# Lightning Python Introduction

Resources used for this tutorial:
* Course materials from [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335) from the `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).
* A sequence of [Jupyter notebooks featuring the "12 Steps to Navier-Stokes"](https://github.com/barbagroup/CFDPython) (see also: http://lorenabarba.com/)
* [An Introduction to Python](https://wiki.uchicago.edu/display/phylabs/An+Introduction+to+Python) from the UChicago Physics Department Undergraduate Labs
* Tutorials for `list` vs `array` such as [Medium.com](https://medium.com/@aakankshaws/arrays-vs-lists-in-python-db8b26ce5cc3) and [pythoncentral.io](https://www.pythoncentral.io/the-difference-between-a-list-and-an-array/)


## Libraries

something deleted

Python libraries are collections of functions and methods that allows you to perform many actions without writing your code. We can import various libraries of functions to expand the capabilities of Python in our programs. Since Python is an object oriented, high-level programming language, this means that we get *classes* that have various "methods" or "functions" as members of that class, or group of functions and internal information specific to that class.

See also: https://www.quora.com/What-is-a-Python-library-and-what-can-I-use-it-for

In [3]:
# <-- comments in python are denoted by the pound sign, like this one

import numpy as np                 # we import the Numerical Python array library using a common name `np`
import matplotlib.pyplot as plt  # import the matplotlib plotting library as `plt`, again a common name

We are importing one library named `numpy` and we are importing a module called `pyplot` of a big library called `matplotlib`. We rename the library `numpy` to a shorter, easier (and much more common) name `np`, and something similar for `pyplot`, for which we use `plt`. 

To use a function belonging to one of these libraries, we have to tell Python where to look for it. For that, each function name is written following the library name, with a dot in between.

#### EXERCISE: `linspace`

Look up the `numpy` function `linspace()`, and use it to create an *array* with 10 equally spaced numbers between a start and end:

In [47]:
myarray = ?
print(myarray)

SyntaxError: invalid syntax (<ipython-input-47-cbe0433d7152>, line 1)

## Strings

A few basic string manipulation examples:

In [34]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, " has length:", len(hello))

hello  has length: 5


In [36]:
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

hello world


In [37]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello world 12


#### EXERCISE: fixed width strings

In [51]:
hw12fixed = '%s %s %d' % (hello, world, 12)  # change this to print a fixed width
print(hw12fixed)

hello world 12


String objects have a bunch of useful methods; for example:

In [52]:
s = "hello"
print(s.capitalize())           # Capitalize a string; prints "Hello"
print(s.upper())                # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))               # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))              # Center a string, padding with spaces; prints " hello "
print('  world '.strip())      # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
world


#### EXERCISE: Search and replace in strings

Replace all instances of "l" with "ell" in the string `s`

In [53]:
print(s)  # Replace all instances of "l" with "ell" in the string `s`

hello


## Arrays and Lists

Arrays and lists are both used in Python to store data, but they don't serve exactly the same purposes. They both can be used to store any data type (real numbers, strings, etc), and they both can be indexed and iterated through, but the similarities between the two don't go much further. 

The main difference between a list and an array is the functions that you can perform to them. For example, you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. If you try to divide a list by 3, Python will tell you that it can't be done, and an error will be thrown. 

Lists are built into python. Basically, lists are a collection of things. They are the efficient way of storing data. You can create a list of anything, with any data type like `a = [1, 2.0, “hello”]`. You will see that the type of `a` is list.

In [15]:
a = [1, 2.0, "hello"]
type(a)

list

In [21]:
x = np.array([3, 6, 9, 12])
type(x)
x/3.0
print(x)

[ 3  6  9 12]


If you tried to do the same with a list, it would very similar, except you wouldn't get a valid output because the code would throw an error.

In [22]:
y = [3, 6, 9, 12]
type(y)
y/3.0
print(y)

TypeError: unsupported operand type(s) for /: 'list' and 'float'

It does take an extra step to use arrays because they have to be declared while lists don't because they are part of Python's syntax, so lists are generally used more often between the two, which works fine most of the time. However, if you're going to perform arithmetic functions to your lists, you should really be using arrays instead. Additionally, arrays will store your data more compactly and efficiently, so if you're storing a large amount of data, you may consider using arrays as well.

### Slicing Arrays

In `numpy`, you can look at portions of arrays in the same way as in `Matlab`, with a few extra tricks thrown in.  Let's take an array of values from 1 to 5.

In [6]:
myvals = np.array([1, 2, 3, 4, 5])
myvals

array([1, 2, 3, 4, 5])

Python uses a **zero-based index**, so let's look at the first and last element in the array `myvals`

In [7]:
myvals[0], myvals[4]

(1, 5)

Arrays can also be 'sliced', grabbing a range of values.  Let's look at the first three elements

In [8]:
myvals[0:3]

array([1, 2, 3])

Note here, the slice is inclusive on the front end and exclusive on the back, so the above command gives us the values of `myvals[0]`, `myvals[1]` and `myvals[2]`, but not `myvals[3]`.

In [45]:
nums = list(range(5)) # range is a built-in function that creates a list of integers
print(nums)           # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])      # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])       # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])       # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])        # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])      # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9]    # Assign a new sublist to a slice
print(nums)           # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


### Additional array manipulation

In [23]:
a = [1, 2, 3, 4]
b = [9, 8, 7, 6]

In [26]:
print('[a,b] =', [a,b])

[a,b] = [[1, 2, 3, 4], [9, 8, 7, 6]]
a + b = [1, 2, 3, 4, 9, 8, 7, 6]
2*a = [1, 2, 3, 4, 1, 2, 3, 4]


In [27]:
print('a + b =', a + b)

a + b = [1, 2, 3, 4, 9, 8, 7, 6]


In [28]:
print('2*a =', 2*a)

2*a = [1, 2, 3, 4, 1, 2, 3, 4]


The first line is a nested list (as expected). In the second line, Python interprets `+` to mean "add second list to the end of the first list." In the third line, Python interprets `2*a` to be `a + a` and again appends the second list to the first.